name: Docker Build & Push

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      new_tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: ${{ secrets.docker_username }}/${{ inputs.app_name }}:${{ inputs.new_tag }}
      IMAGE_LATEST: ${{ secrets.docker_username }}/${{ inputs.app_name }}:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Docker Build
        run: |
          docker build -f infra/docker/prod.Dockerfile -t "$IMAGE_VERSION" -t "$IMAGE_LATEST" .

      - name: Push Docker Image
        run: |
          docker push "$IMAGE_VERSION"
          docker push "$IMAGE_LATEST"
